version: '3.8'

services: 
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 80:80
    volumes:
       - ./src:/var/www/html/

    # Overrides default command so things don't shut down after the process ends.


    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    

    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql:rw
      - ./init-sql:/docker-entrypoint-initdb.d:rw
    environment:
      MYSQL_ROOT_PASSWORD: hp1234
      MYSQL_DATABASE: hp
      MYSQL_USER: hp
      MYSQL_PASSWORD: hp1234
    ports:
    - 3306:3306

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
volumes:
  mariadb-data:
